# Ontrack environment for Nemerosa
version: "3"

services:
   # Jenkins
   jenkins:
      image: "jenkins:2.32.2-alpine"
      networks:
         - proxy
      deploy:
         labels:
            - com.df.notify=true
            - com.df.distribute=true
            - com.df.serviceDomain=${JENKINS_DOMAIN_NAME}
            - com.df.servicePath=/
            - com.df.port=8080

networks:
   proxy:
      external: true
