version: "3"

services:
   # InfluxDB
   influxdb:
      image: influxdb:1.2.0-alpine
      environment:
         INFLUXDB_GRAPHITE_ENABLED: "true"
      networks:
         - proxy
      deploy:
         labels:
            - com.df.notify=true
            - com.df.distribute=true
            - com.df.serviceDomain=${MONITORING_DOMAIN_NAME}
            - com.df.servicePath=/influxdb
            # Administrative interface is deprecated and is therefore NOT exposed here
            - com.df.port=8086
   # TODO Prometheus
   # TODO Grafana
   grafana:
      image: grafana/grafana:4.1.1
      networks:
         - proxy
      deploy:
         labels:
            - com.df.notify=true
            - com.df.distribute=true
            - com.df.serviceDomain=${GRAFANA_DOMAIN_NAME}
            - com.df.servicePath=/
            - com.df.port=3000
      environment:
            # TODO Use Docker secrets
            GF_SECURITY_ADMIN_PASSWORD: "admin"

networks:
   proxy:
      external: true
